### ISSUE TITLE
Error: Cannot read property 'sequelize' of undefined

### ISSUE THREAD

**Issue by paulxtiseo** [sequelize/cli#105]
Trying to execute a first migration in a new project.

Here's the error
```
MacPro148:server_ah$ sequelize db:migrate

Sequelize [Node: 0.12.0, CLI: 1.3.1, ORM: 2.0.3]

Loaded configuration file 'migrations/config.json'.
Using environment 'development'.
== 20150304090000-CreateUpdatedTimeStampFunction: migrating =======
Possibly unhandled TypeError: Cannot read property 'sequelize' of undefined
    at Object.module.exports.up (/Documents/Repositories/AEX/server_ah/migrations/20150304090000-CreateUpdatedTimeStampFunction.js:16:23)
    at Object.tryCatcher (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/util.js:24:31)
    at Object.ret (eval at <anonymous> (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promisify.js:154:12), <anonymous>:13:39)
    at module.exports.redefine.Class._exec (/usr/local/lib/node_modules/sequelize-cli/node_modules/umzug/lib/migration.js:49:23)
    at module.exports.redefine.Class.up (/usr/local/lib/node_modules/sequelize-cli/node_modules/umzug/lib/migration.js:33:17)
    at null.<anonymous> (/usr/local/lib/node_modules/sequelize-cli/node_modules/umzug/index.js:78:28)
    at Object.tapHandler (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/finally.js:64:43)
    at Object.tryCatcher (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

and the migration file:

```javascript
module.exports = {
  up: function(migration, DataTypes, done) {
    
    var theSql = [
      'CREATE OR REPLACE FUNCTION set_updated_timestamp() ',
      'RETURNS TRIGGER ',
      'LANGUAGE plpgsql ',
      'AS $$ ',
      'BEGIN ',
      '  NEW.updated := now(); ',
      '  RETURN NEW; ',
      'END; ',
      '$$;'
    ].join('\n');

    migration.migrator.sequelize.query(theSql)
      .finally(done);
  },

  down: function(migration, DataTypes, done) {
    migration.migrator.sequelize.query('DROP FUNCTION IF EXISTS set_updated_timestamp();')
      .finally(done);
  }
};
```

Also, the above is the first migration. If I comment it out, the second is a `migration.createTable("Operator", ...` call, and the table gets created just fine. So, migrations work...generally. :)

**Comment by limetwister** [comment]
I ran into this as well ... still looking.

**Comment by paulxtiseo** [comment]
@limetwister, you now apparently need to use `migration.sequelize.query()` to run raw sql.

**Comment by limetwister** [comment]
wow thanks ... was just about to throw in the towel for a couple of hours to let my brain stop going in circles.


cheers!

**Comment by sdepold** [comment]
Did you migrate to a newer version of the cli lately?

**Comment by paulxtiseo** [comment]
@sdepold, I did not. I was going off the various hits on Google for running raw sql, which probably work off older versions. Maybe I didn't look in the right place in the online docs, but I don't see any good coverage on this frequent need in the migration section.

**Comment by limetwister** [comment]
on 1.3.1 ... seem to be past that error now ... on to the problems in my script ... thanks all

**Comment by sdepold** [comment]
So the issue here is that we are no longer passing the weird migrator object which referenced the queryinterface which referenced the sequelize instance but just the queryinterface as the first argument.

**Comment by bloodymind** [comment]
After using `migration.sequelize.query` i have a new issue :/ 

`SequelizeDatabaseError: syntax error at end of input`

The query is correct i can run it in PgAdmin4 without issues.
