### ISSUE TITLE
Got an error when run a migration with DataTypes.ENUM: number[]

### ISSUE THREAD

**Issue by gomez-git** [sequelize/cli#1275]
## What you are doing?

I wrote a migration file and try to up a migration.

```js
module.exports = {
  async up(queryInterface, DataTypes) {
    await queryInterface.createTable('accounts', {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      amo_id: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
      tld: {
        type: DataTypes.ENUM('ru', 'com'),
        allowNull: false,
      },
      installation_id: {
        type: DataTypes.INTEGER,
        unique: true,
        allowNull: true,
      },
      merge_to: {
        type: DataTypes.ENUM('old', 'new'),
        allowNull: false,
        defaultValue: 'old',
      },
      merge_new_contacts: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true,
      },
      max_custom_fields_count: {
        type: DataTypes.INTEGER,
        allowNull: false,
        defaultValue: 5,
      },
      custom_fields_ids: {
        type: DataTypes.JSON,
        allowNull: false,
        defaultValue: [],
      },
      custom_fields_filters: {
        type: DataTypes.JSON,
        allowNull: false,
        defaultValue: [],
      },
      is_test_license: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
      },
      license_expires_at: {
        type: DataTypes.DATE,
        allowNull: false,
      },
      requests_limit: {
        type: DataTypes.ENUM(1, 2, 3, 4),
        allowNull: false,
        defaultValue: 1,
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.fn('NOW'),
      },
      updated_at: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.fn('NOW'),
      },
    });
    await queryInterface.addConstraint('accounts', {
      type: 'unique',
      fields: ['amo_id', 'tld'],
    });
  },

  async down(queryInterface) {
    await queryInterface.dropTable('accounts');
  },
};
```

Also tried:
```js
      requests_limit: {
        type: DataTypes.ENUM(1, 2, 3, 4),
        allowNull: false,
      },
      requests_limit: {
        type: DataTypes.ENUM,
        values: [1, 2, 3, 4],
        allowNull: false,
        defaultValue: 1,
      },
      requests_limit: {
        type: DataTypes.ENUM({ values: [1, 2, 3, 4] }),
        allowNull: false,
        defaultValue: 1,
      },
      requests_limit: {
        type: DataTypes.ENUM([1, 2, 3, 4]),
        allowNull: false,
        defaultValue: 1,
      },
      requests_limit: {
        type: DataTypes.ENUM('1', '2', '3', '4'),
        allowNull: false,
        defaultValue: '1',
      },
      requests_limit: {
        type: DataTypes.DataTypes.ENUM(1, 2, 3, 4),
        allowNull: false,
        defaultValue: 1,
      },
      requests_limit: {
        type: DataTypes.DataTypes.postgres.ENUM(1, 2, 3, 4),
        allowNull: false,
        defaultValue: 1,
      },
```

## What do you expect to happen?
All will be ok.

## What is actually happening?
I've got an error:
```sh
$ npx sequelize db:migrate --debug

Sequelize CLI [Node: 16.16.0, CLI: 6.6.0, ORM: 6.29.0]

Loaded configuration file "server/db/config.js".
Using environment "development".
== 20220906112930-create-accounts: migrating =======

ERROR: Error
    at Query.run (~/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at ~/node_modules/sequelize/lib/sequelize.js:315:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryInterface.createTable (~/node_modules/sequelize/lib/dialects/abstract/query-interface.js:98:12)
    at async Object.up (~/server/db/migrations/20220906112930-create-accounts.cjs:3:5)
EXTRA MESSAGE: type "public.enum_accounts_requests_limit" does not exist
```

__Dialect:__ postgres
__Database version:__ 10.22 (Ubuntu 10.22-0ubuntu0.18.04.1) / 14.6 (Debian 14.6-1.pgdg110+1)
__Sequelize CLI version:__ 6.6.0 
__Sequelize version:__ 6.29.0 / 6.29.3

**Comment by malik-samad** [comment]
I am not able to replicate the error with the message you have attached. I copied your migration code and it worked fine for me. here is the migration file that I used.

```
'use strict';
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.createTable('Users', {
      id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      amo_id: {
        type: Sequelize.INTEGER,
        allowNull: false,
      },
      tld: {
        type: Sequelize.ENUM('ru', 'com'),
        allowNull: false,
      },
      installation_id: {
        type: Sequelize.INTEGER,
        unique: true,
        allowNull: true,
      },
      merge_to: {
        type: Sequelize.ENUM('old', 'new'),
        allowNull: false,
        defaultValue: 'old',
      },
      merge_new_contacts: {
        type: Sequelize.BOOLEAN,
        allowNull: false,
        defaultValue: true,
      },
      max_custom_fields_count: {
        type: Sequelize.INTEGER,
        allowNull: false,
        defaultValue: 5,
      },
      custom_fields_ids: {
        type: Sequelize.JSON,
        allowNull: false,
        defaultValue: [],
      },
      custom_fields_filters: {
        type: Sequelize.JSON,
        allowNull: false,
        defaultValue: [],
      },
      is_test_license: {
        type: Sequelize.BOOLEAN,
        allowNull: false,
      },
      license_expires_at: {
        type: Sequelize.DATE,
        allowNull: false,
      },
      requests_limit: {
        type: Sequelize.ENUM('1', '2', '3', '4'),
        allowNull: false,
        defaultValue: '1',
      },
      created_at: {
        type: Sequelize.DATE,
        allowNull: false,
        defaultValue: Sequelize.fn('NOW'),
      },
      updated_at: {
        type: Sequelize.DATE,
        allowNull: false,
        defaultValue: Sequelize.fn('NOW'),
      },
    });
    await queryInterface.addConstraint('Users', {
      type: 'unique',
      fields: ['amo_id', 'tld'],
    });
  },
  async down(queryInterface, Sequelize) {
    await queryInterface.dropTable('Users');
  },
};
```
