### ISSUE TITLE
require of ES module wrap-ansi

### ISSUE THREAD

**Issue by b1ek** [sequelize/cli#1303]
## What you are doing?
Running migrations

## What do you expect to happen?
I expected `sequelize-cli` to run

## What is actually happening?
```
/opt/code # npx sequelize-cli db:migrate
/opt/code/node_modules/cliui/build/index.cjs:293
const wrap = require('wrap-ansi');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/code/node_modules/wrap-ansi/index.js from /opt/code/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /opt/code/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/opt/code/node_modules/cliui/build/index.cjs:293:14)
    at Object.<anonymous> (/opt/code/node_modules/yargs/build/index.cjs:2861:12)
    at Object.<anonymous> (/opt/code/node_modules/yargs/index.cjs:5:30)
    at Object.<anonymous> (/opt/code/node_modules/sequelize-cli/lib/core/yargs.js:10:37)
    at Object.<anonymous> (/opt/code/node_modules/sequelize-cli/lib/sequelize:4:37) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.2.0
/opt/code # 
```

__Sequelize CLI version:__ 6.6.0
__Sequelize version:__ 6.31.1

The error is in `sequelize-cli`, since the code in stack trace did not reach any of my code

**Comment by b1ek** [comment]
The error was caused by a broken dependency resolution, which installed `wrap-ansi` of `8.1` version that requires ESM, instead of `7.0` verison
