### ISSUE TITLE
Sequelize needs MySQL package. 

### ISSUE THREAD

**Issue by gauravbhavsar** [sequelize/cli#134]
getting this error in command promt, I am using MS SQL while it required MySQL package ?

E:\gaurav\Projects\Node(ORM_MSSQL)\node_modules\sequelize\lib\sequelize.js:187
      throw new Error('The dialect ' + this.getDialect() + ' is not supported.
            ^
Error: The dialect mysql is not supported. (Error: Please install mysql package manually)
    at new module.exports.Sequelize (E:\gaurav\Projects\Node(ORM_MSSQL)\node_modules\sequelize\lib\sequelize.js:187:13)
    at Object.<anonymous> (E:\gaurav\Projects\Node(ORM_MSSQL)\server.js:19:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by gauravbhavsar** [comment]
I forgot to define mssql in dialect, so by default it will take MySQL.
