### ISSUE TITLE
error thrown at new module.exports.Sequelize (/.../sequelize/lib/sequelize.js:183:13)

### ISSUE THREAD

**Issue by tommedema** [sequelize/cli#137]
I've got a fresh node installation, and a fresh global sequalize-cli installation. I created a migration and model file using `sequelize model:create --name Post --attributes body:text,source:enum,source_post_id:string`

When I then run `sequelize db:migrate` I get the following error thrown without any helpful pointers:

    tom@tom-UX32VD:~/projects/chambeng/chambeng-api$ sequelize db:migrate
    Sequelize [Node: 0.12.2, CLI: 1.7.0, ORM: 3.1.0]

    Loaded configuration file "config/config.json".
    Using environment "development".
        at new module.exports.Sequelize (/home/tom/projects/chambeng/chambeng-api/node_modules/sequelize/lib/sequelize.js:183:13)
        at getSequelizeInstance (/usr/local/lib/node_modules/sequelize-cli/lib/tasks/db.js:203:10)
        at getMigrator (/usr/local/lib/node_modules/sequelize-cli/lib/tasks/db.js:208:21)
        at Object.module.exports.db:migrate.task (/usr/local/lib/node_modules/sequelize-cli/lib/tasks/db.js:23:7)
        at Gulp.gulp.task.aliases (/usr/local/lib/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:14:14)
        at module.exports (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
        at Gulp.Orchestrator._runTask (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
        at Gulp.Orchestrator._runStep (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
        at Gulp.Orchestrator.start (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
        at /usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:129:20
        at process._tickCallback (node.js:355:11)
        at Function.Module.runMain (module.js:503:11)
        at startup (node.js:129:16)
        at node.js:814:3

Even when I remove all the columns (create an empty table), the problem remains. It also remains when I only create a migration (not a model).

Running node 0.12.2.

Any idea what's going on?

**Comment by tommedema** [comment]
Nevermind, I had to do a `npm install mysql` locally rather than globally
