### ISSUE TITLE
migration fails but SequelizeMeta record is still created (sqlite3)

### ISSUE THREAD

**Issue by kgraves** [sequelize/cli#142]
This happened when I ran a migration that was changing a column, via the `changeColumn` function. I was able to reproduce by manually undoing the migration and running it again. Initially the column, a foreign key, referenced the wrong table (copy-pasta error). Here's what that part of the original migration looked like:

```
...
product_category_id: {
  type: Sequelize.INTEGER,
  allowNull: false,
  references: {
    model: 'user',
    key: 'id'
  }
},
...
```

and the new, corrected migration:
```
module.exports = {
  up: function (queryInterface, Sequelize) {
    queryInterface.changeColumn('product', 'product_category_id', {
      type: Sequelize.INTEGER,
      allowNull: false,
      references: {
        model: 'product_category',
        key: 'id'
      }
    });
  },

  down: function (queryInterface, Sequelize) {
    queryInterface.changeColumn('product', 'product_category_id', {
      type: Sequelize.INTEGER,
      allowNull: false,
      references: {
        model: 'user',
        key: 'id'
      }
    });
  }
};
```

Here is what happened when I ran the migration:
```
$ sequelize db:migrate --config=config/sequelize.json 
Sequelize [Node: 0.10.25, CLI: 1.7.0, ORM: 3.1.1]

Loaded configuration file "config/sequelize.json".
Using environment "development".
Using gulpfile ~/Documents/gits/ph-ecom-web/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:migrate'...
Finished 'db:migrate' after 107 ms
== 20150611114153-change_product_category_id_on_product: migrating =======
Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: temp.product_category
    at module.exports.Query.formatError (/home/kg/Documents/gits/ph-ecom-web/node_modules/sequelize/lib/dialects/sqlite/query.js:242:16)
    at /home/kg/Documents/gits/ph-ecom-web/node_modules/sequelize/lib/dialects/sqlite/query.js:48:31
    at Statement.errBack (/home/kg/Documents/gits/ph-ecom-web/node_modules/sqlite3/lib/sqlite3.js:16:21)
== 20150611114153-change_product_category_id_on_product: migrated (0.034s)
$
```

I thought the last line was weird considering that there was an error. So I checked the SequelizeMeta table and saw that my migration had been marked as a success:
```
sqlite> select * from SequelizeMeta;
20150603180731-create_user_table.js
20150609140828-create_address_table.js
20150610160434-add_name_to_user.js
20150610160459-add_is_distributor_to_user.js
20150610171041-create_product_table.js
20150610211850-create_product_category_table.js
20150611114153-change_product_category_id_on_product.js <---- failed migration
sqlite> 
```

**Comment by mickhansen** [comment]
You need to return the promises, since you arent right now umzug just assumed an empty migration (would probably be saner if that just failed though).

**Comment by kgraves** [comment]
I'm not sure I understand. Are you saying that `changeColumn(...)` returns a promise and that I need to return that from my `up` function?

Also, regardless of there being an error, syntactically or semantically, shouldn't the migration not be marked as a success when it fails? It's marking a failure as a success, correct?

**Comment by kgraves** [comment]
ahhh I'm now seeing example on this project's readme. Looks like the docs for Sequelize need to be updated some.

So then is it standard to return a promise and put a try/catch around my `.changeColumn` like so?:
```
module.exports = {
  up: function (queryInterface, Sequelize) {
    return new Promise(function(resolve, reject) {
      try {
        queryInterface.changeColumn('product', 'product_category_id', {
          type: Sequelize.INTEGER,
          allowNull: false,
          references: {
            model: 'product_category',
            key: 'id'
          }
        });
        resolve();
      } catch(e) {
        reject(e);
      }
    });
  },
```

**Comment by mickhansen** [comment]
All sequelize calls are asynchronous, right now you are treating changeColumn as sync. You either need to use the migration callback or return a promise to the migration:

```js
module.exports = {
  up: function (queryInterface, Sequelize) {
    queryInterface.changeColumn('product', 'product_category_id', {
          type: Sequelize.INTEGER,
          allowNull: false,
          references: {
            model: 'product_category',
            key: 'id'
          }
        });
  }
};
```

**Comment by kgraves** [comment]
Ah ok, got it. That makes sense, I'll try it out.

Thanks for your help Mick :+1:
