### ISSUE TITLE
Error with sequelize model:create in a fresh project

### ISSUE THREAD

**Issue by pierredavidbelanger** [sequelize/cli#185]
Here is what I did:

Init a new fresh project (all to the defaults)
```
$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (sequelizeclitest) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /private/tmp/sequelizeclitest/package.json:

{
  "name": "sequelizeclitest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this ok? (yes) 
```

Install sequelize, sequelize-cli and pg
```
$ npm install sequelize sequelize-cli pg --save
npm WARN package.json sequelizeclitest@1.0.0 No description
npm WARN package.json sequelizeclitest@1.0.0 No repository field.
npm WARN package.json sequelizeclitest@1.0.0 No README data
npm WARN unmet dependency /private/tmp/sequelizeclitest/node_modules/sequelize-cli/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream requires through2@'^0.6.1' but will load
npm WARN unmet dependency /private/tmp/sequelizeclitest/node_modules/sequelize-cli/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2,
npm WARN unmet dependency which is version 0.6.5
pg@4.4.2 node_modules/pg
├── packet-reader@0.2.0
├── pg-connection-string@0.1.3
├── buffer-writer@1.0.0
├── generic-pool@2.1.1
├── semver@4.3.6
├── pg-types@1.10.0 (postgres-bytea@1.0.0, postgres-date@1.0.0, postgres-array@1.0.0, ap@0.2.0, postgres-interval@1.0.0)
└── pgpass@0.0.3 (split@0.3.3)

sequelize@3.9.0 node_modules/sequelize
├── shimmer@1.0.0
├── dottie@0.3.1
├── depd@1.1.0
├── toposort-class@1.0.1
├── generic-pool@2.2.0
├── inflection@1.7.1
├── node-uuid@1.4.3
├── semver@5.0.3
├── validator@4.0.6
├── wkx@0.1.0
├── bluebird@2.9.34
├── wellknown@0.3.4 (minimist@1.1.3, concat-stream@1.5.0)
├── moment-timezone@0.4.0
├── lodash@3.10.1
└── moment@2.10.6

sequelize-cli@1.9.1 node_modules/sequelize-cli
├── yargs@1.3.3
├── umzug@1.6.0 (redefine@0.2.1)
├── resolve@1.1.6
├── findup-sync@0.2.1 (glob@4.3.5)
├── bluebird@2.10.1
├── fs-extra@0.16.5 (jsonfile@2.2.2, graceful-fs@3.0.8, rimraf@2.4.3)
├── gulp-help@1.3.4 (gulp-util@3.0.6)
├── gulp@3.9.0 (pretty-hrtime@1.0.0, interpret@0.6.6, deprecated@0.0.1, archy@1.0.0, tildify@1.1.1, minimist@1.2.0, v8flags@2.0.10, chalk@1.1.1, semver@4.3.6, orchestrator@0.3.7, gulp-util@3.0.6, liftoff@2.2.0, vinyl-fs@0.3.14)
├── js-beautify@1.5.10 (mkdirp@0.5.1, config-chain@1.1.9, nopt@3.0.4)
├── lodash@3.10.1
├── moment@2.10.6
└── cli-color@0.3.3 (d@0.1.1, timers-ext@0.1.0, memoizee@0.3.9, es5-ext@0.10.7)
```

Init the sequelize structure
```
$ ./node_modules/.bin/sequelize init

Sequelize [Node: 4.0.0, CLI: 1.9.1, ORM: 3.9.0]

Using gulpfile /private/tmp/sequelizeclitest/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'init:config'...
Created "config/config.json"
Finished 'init:config' after 1.74 ms
Successfully created migrations folder at "/private/tmp/sequelizeclitest/migrations".
Successfully created seeders folder at "/private/tmp/sequelizeclitest/seeders".
Starting 'init:models'...
Successfully created models folder at "/private/tmp/sequelizeclitest/models".
Loaded configuration file "config/config.json".
Using environment "development".
Finished 'init:models' after 2 ms
Finished 'init' after 75 μs
```

Create a simple `User` model with only one attribute
```
$ ./node_modules/.bin/sequelize model:create --name User --attributes email

Sequelize [Node: 4.0.0, CLI: 1.9.1, ORM: 3.9.0]

Loaded configuration file "config/config.json".
Using environment "development".
Using gulpfile /private/tmp/sequelizeclitest/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'model:create'...
'model:create' errored after 1.2 ms
    at eval (lodash.templateSources[2]:18:32)
    at Array.forEach (native)
    at eval (lodash.templateSources[2]:14:26)
    at Object.module.exports.render (/private/tmp/sequelizeclitest/node_modules/sequelize-cli/lib/helpers/template-helper.js:23:40)
    at Object.module.exports.generateFileContent (/private/tmp/sequelizeclitest/node_modules/sequelize-cli/lib/helpers/model-helper.js:36:29)
    at Object.module.exports.generateFile (/private/tmp/sequelizeclitest/node_modules/sequelize-cli/lib/helpers/model-helper.js:45:41)
    at Object.module.exports.model:create.task (/private/tmp/sequelizeclitest/node_modules/sequelize-cli/lib/tasks/model.js:131:21)
    at Gulp.gulp.task.aliases (/private/tmp/sequelizeclitest/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:14:14)
    at module.exports (/private/tmp/sequelizeclitest/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/private/tmp/sequelizeclitest/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/private/tmp/sequelizeclitest/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/private/tmp/sequelizeclitest/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /private/tmp/sequelizeclitest/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3
```

Some more info
```
$ node --version
v4.0.0
$ npm --version
2.14.2
$ uname -a
Darwin MacBook-Pro-de-Pierre-David.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by Americas** [comment]
there is no default attribute type, so please run something like this:

```bash
./node_modules/.bin/sequelize model:create --name User --attributes email:string
```

**Comment by pierredavidbelanger** [comment]
Indeed, it works now. It makes sense.
Thank you, and sorry for this n00b question ;)
