### ISSUE TITLE
sequelize db:migrate not working

### ISSUE THREAD

**Issue by Vietworm** [sequelize/cli#187]
I create migration as following:
```
sequelize migration:create --name articles --env development
```
and then define migrations `articles` generated.
Next, type: `sequelize db:migrate`
Of course, I did configuration database information on `config.js` before that. But query return error,i did uninstall sequelize-cli and reinstall but still not working. :(

I hope, have someone support my issue.

Thanks & Best regards,

```
Sequelize [Node: 3.2.0, CLI: 1.9.1, ORM: 3.9.0]

Loaded configuration file "config\config.json".
Using environment "development".
Using gulpfile ~\AppData\Roaming\npm\node_modules\sequelize-cli\lib\gulpfile.js
Starting 'db:migrate'...
'db:migrate' errored after 15 ms
    at new Sequelize (C:\Users\0xgi\Desktop\node_modules\sequelize\lib\sequelize.js:202:11)
    at getSequelizeInstance (C:\Users\0xgi\AppData\Roaming\npm\node_modules\sequelize-cli\lib\tasks\db.js:2
82:10)
    at getMigrator (C:\Users\0xgi\AppData\Roaming\npm\node_modules\sequelize-cli\lib\tasks\db.js:287:21)
    at Object.module.exports.db:migrate.task (C:\Users\0xgi\AppData\Roaming\npm\node_modules\sequelize-cli\
lib\tasks\db.js:23:7)
    at Gulp.gulp.task.aliases (C:\Users\0xgi\AppData\Roaming\npm\node_modules\sequelize-cli\lib\helpers\gul
p-helper.js:14:14)
    at module.exports (C:\Users\0xgi\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\gulp\node_
modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\0xgi\AppData\Roaming\npm\node_modules\sequelize-cli\node_module
s\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\0xgi\AppData\Roaming\npm\node_modules\sequelize-cli\node_module
s\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\0xgi\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\g
ulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\0xgi\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\gulp\bin\gulp.js:129:20
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
    at Function.Module.runMain (module.js:473:11)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by struCoder** [comment]
Me too...
![image](https://cloud.githubusercontent.com/assets/6498477/10123914/dc2d3448-6578-11e5-9506-b5d4f5f42eba.png)

**Comment by timrourke** [comment]
I have the same issue.

**Comment by struCoder** [comment]
@Vietworm @timrourke 
Maybe i found the wrong msg reason..
First, you should `npm install mysql --save`

just this.

**Comment by sdepold** [comment]
Yeah I was wondering the same. Did you install the db connector? The current situation is far from perfect and the CLI should tell you about that in a better way, but maybe this already fixes your problems.

**Comment by timrourke** [comment]
@sdepold @struCoder I'm using postrgesql, not mysql. I have pg and pg-hstore already installed in the project and have been using Sequelize as an ORM just fine. Is there some other db connector I need?

**Comment by sdepold** [comment]
@timrourke @Vietworm can you edit 
`node_modules/sequelize-cli/lib/tasks/db.js`

and change the lines around line 282 to this:

```
  options = _.assign({ logging: logMigrator }, options);
  try {
    return new Sequelize(config.database, config.username, config.password, options);
  } catch (e) {
    console.warn(e);
    throw e;
  }
```

?

**Comment by sdepold** [comment]
I think it would make sense to have that add that to the CLI itself.

**Comment by timrourke** [comment]
Same error for me: 

```
Sequelize [Node: 0.12.2, CLI: 1.9.1, ORM: 3.9.0]

Loaded configuration file "config/config.json".
Using environment "development".
Using gulpfile /usr/local/lib/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:migrate'...
'db:migrate' errored after 28 ms
    at new Sequelize (/usr/local/lib/node_modules/sequelize/lib/sequelize.js:202:11)
    at getSequelizeInstance (/usr/local/lib/node_modules/sequelize-cli/lib/tasks/db.js:282:10)
    at getMigrator (/usr/local/lib/node_modules/sequelize-cli/lib/tasks/db.js:287:21)
    at Object.module.exports.db:migrate.task (/usr/local/lib/node_modules/sequelize-cli/lib/tasks/db.js:23:7)
    at Gulp.gulp.task.aliases (/usr/local/lib/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:14:14)
    at module.exports (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

My migrations file is very simple right now, and just looks like this:

```
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    /*
      Add altering commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.createTable('users', { id: Sequelize.INTEGER });
    */
    queryInterface.addColumn(
      'Gradients',
      'angle',
      {
        type: Sequelize.FLOAT,
        defaultValue: 0
      }
    );
  },

  down: function (queryInterface, Sequelize) {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.dropTable('users');
    */
    queryInterface.removeColumn(
      'Gradients',
      'angle'
    );
  }
};
```

**Comment by Vietworm** [comment]
Thanks @sdepold, @struCoder and @timrourke suggested solved my issues.

I'm change the lines around line 282 following @sdepold  `code`

```javascript
options = _.assign({ logging: logMigrator }, options);
  try {
    return new Sequelize(config.database, config.username, config.password, options);
  } catch (e) {
    console.warn(e);
    throw e;
  }
```
It works, I'm run `sequelize db:migrate`. It suggesteds me install 2 modules `pg` and `pg-hstore` with `global` because I'm using dialect `postgres`.

Thank you so much!.


```
C:\Users\0xgi\Desktop\sequelize>sequelize migration:create --name articles

Sequelize [Node: 3.2.0, CLI: 1.9.1, ORM: 3.9.0]

Loaded configuration file "config\config.json".
Using environment "development".
Using gulpfile ~\AppData\Roaming\npm\node_modules\sequelize-cli\lib\gulpfile.js
Starting 'migration:create'...
Successfully created migrations folder at "C:\Users\0xgi\Desktop\sequelize\migrations".
New migration was created at C:\Users\0xgi\Desktop\sequelize\migrations\20150929212834-articles.js .
Finished 'migration:create' after 5.58 ms

C:\Users\Vietworm\Desktop\sequelize>sequelize db:migrate

Sequelize [Node: 3.2.0, CLI: 1.9.1, ORM: 3.9.0]

Loaded configuration file "config\config.json".
Using environment "development".
Using gulpfile ~\AppData\Roaming\npm\node_modules\sequelize-cli\lib\gulpfile.js
Starting 'db:migrate'...
Finished 'db:migrate' after 93 ms
== 20150929212834-articles: migrating =======
== 20150929212834-articles: migrated (0.049s)

C:\Users\Vietworm\Desktop\sequelize> 
```

**Comment by timrourke** [comment]
Thanks, @Vietworm !

There it is, I just installed `pg` and `pg-hstore` globally, and I'm suddenly getting appropriate error messages regarding the db operation, not an all-out failure. Think that should have solved the issue for me, will report back if I bump into anything else.

**Comment by timrourke** [comment]
@sdepold I would add a note in the readme about making sure the db connector is installed globally, but I'm not familiar enough with this library to write anything sensical. 

Do you suspect this issue occurred because sequelize-cli was installed only globally, not in the local project, and I was assuming it would find the `pg` and `pg-hstore` dependencies in the local project? I'm honestly not sure if this is normal npm behavior or not.

**Comment by sdepold** [comment]
Yeah it should potentially find the modules locally too, but that depends on how sequelize loads them. First of all I'm glad that the issue is fixed for now.

**Comment by rutaihwa** [comment]
I just started to read the cli when I try to do `sequelize model:create --name client --attributes 'id:uuid', 'secret:uuid', 'name:string', 'category:string', 'platform:string', 'email:string', 'access:string', 'url:string'
` I get `Task 'secret:uuid,' is not in your gulpfile` but when I do `model:create with single attribute` it seems to work fine. What it is the issue here?

**Comment by Vietworm** [comment]
@rutaihwa 

You following code syntax models create, take a look.

```
sequelize model:create --name client --attributes id:uuid,secret:uuid
```

Or used `sequelize help:model:create`, to know how to do it.

**Comment by rutaihwa** [comment]
Ahh thanks @Vietworm ! That worked! :+1: can `model:create` create some models with validations or defaults values?

**Comment by Vietworm** [comment]
You read sequelize [documentation](http://docs.sequelizejs.com/en/latest/), may be refer the syntax:
```javascript
'use strict';

    let slug = require('slug');

    module.exports = function (sequelize, DataTypes) {
        let Category = sequelize.define("category", {
            id : {
                type : DataTypes.INTEGER,
                primaryKey : true,
                autoIncrement : true,
                validate: {
                    isInt: {
                        msg: 'Count must be an integer number'
                    }
                }
            },
            count: {
                type: DataTypes.INTEGER,
                defaultValue: 0,
                validate : {
                    isInt : {
                        msg : 'Count must be an integer number'
                    }
                }
            },
            name: {
                type: DataTypes.STRING,
                unique: true,
                allowNull: false
            },
            alias: {
                type :   DataTypes.STRING,
                validate : {
                    isAlias : function (value) {
                        if (typeof value !== 'string' || value.match(__config.regExp.alias_reg)){
                            throw new Error('Alias cannot includes special characters');
                        }
                    }
                }
            }
        }, {
            tableName: 'arr_category',
            timestamps: false,
            hooks: {
                beforeCreate: function (category, op, fn) {
                    category.alias = slug(category.name).toLowerCase();
                    fn(null, category);
                }
            }
        });

        Category.sync();
        return Category
    };
```

Attention to `index.js` in `models` directory. It help you through files in `models` directory.

**Comment by rutaihwa** [comment]
The documentation is clear on writing of models. I just thought you could create that with the `cli`. Its fine. I will stick to doing `model:create` and update the models later to have other things... Thanks!

**Comment by ibunubi** [comment]
i just rename `config.js` to `config.json`
and edit code `model\index.js` to
`var config    = require(__dirname + '/../config/config.json')[env];`

**Comment by corganfuzz** [comment]
I was having the same issue in Windows 10 - 64 bit. I've followed @ibunubi 's suggestion and all I did is change line 8 from 
`var config    = require(__dirname + '/..\config\config.json')[env];`
to
`var config    = require(__dirname + '/../config/config.json')[env];`

which makes me think it's a bug for windows users only. Btw this was a brand new installtion of sequelize-cli inside express. Now it works

**Comment by mzvast** [comment]
On latest 1703 windows 10, following works fine.
//config.js
```
module.exports = {
  "development": {
    "storage": "./server/dev_db.sqlite",
    "dialect": "sqlite"
  },
  "test": {
    "storage": "./server/test_db.sqlite",
    "dialect": "sqlite"
  },
  "production": {
    "storage": "./server/prod_db.sqlite",
    "dialect": "sqlite"
  }
}

```

**Comment by svisuvas** [comment]
I need to setup a demo ORM and finding the way the migration works is not making sense, in this scenario. 
I just want to overwrite my changes and need to do it from scratch, I find it is difficult in this way.
Any simpler method exist?
