### ISSUE TITLE
TypeError when using Connection String

### ISSUE THREAD

**Issue by joshuakarjala** [sequelize/cli#213]
When using 

`"use_env_variable": "DB_CONNECTION_STRING",`

Instead of the object format I get this error. Using the object format everything runs fine.

```
Sequelize [Node: 4.2.1, CLI: 2.0.0, ORM: 3.12.2]

Loaded configuration file "modules/db/config/config.json".
Using environment "development".
Using gulpfile /src/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:migrate'...
'db:migrate' errored after 2.79 ms
TypeError: Cannot read property 'split' of null
    at /src/node_modules/sequelize-cli/lib/tasks/db.js:258:38
    at /src/node_modules/sequelize-cli/node_modules/lodash/index.js:3073:15
    at baseForOwn (/src/node_modules/sequelize-cli/node_modules/lodash/index.js:2046:14)
    at /src/node_modules/sequelize-cli/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/src/node_modules/sequelize-cli/node_modules/lodash/index.js:3346:13)
    at getSequelizeInstance (/src/node_modules/sequelize-cli/lib/tasks/db.js:250:5)
    at getMigrator (/src/node_modules/sequelize-cli/lib/tasks/db.js:293:21)
    at Object.module.exports.db:migrate.task (/src/node_modules/sequelize-cli/lib/tasks/db.js:23:7)
    at Gulp.gulp.task.aliases (/src/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:14:14)
    at module.exports (/src/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/src/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/src/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/src/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /src/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by joshuakarjala** [comment]
Was because of using strings in .env file

eg.

`DB_HOST_STRING=""`
