### ISSUE TITLE
Getting "relation SequelizeMeta already exists" error when running migration 

### ISSUE THREAD

**Issue by mkay581** [sequelize/cli#312]
I am getting an error when trying to run `sequelize db:migrate` for the first time on my server. I do have a few migration files in the migrations/ folder but it doesnt even look like its getting to that point, which makes me suspect its something related to how the SequelizeMeta table is created. 

It looks like the command is trying to create the SequelizeMeta table in my PostgreSQL database, but seems to already exist. I even tried removing the table manually in the database and re-running the script and still get this message. It seems that this would work if the query was `CREATE TABLE IF EXISTS "SequelizeMeta"` instead of  `CREATE TABLE "SequelizeMeta"` but doesn't seem like there is a way to change this query without changing the sequelize-cli code.

Can anyone help out? Thanks in advance.

FYI: Here is the error message I get:

```bash
Sequelize [Node: 6.2.1, CLI: 2.4.0, ORM: 3.23.3, pg: ^5.1.0]
Loaded configuration file "config/config.js".
        Using environment "production".
{ SequelizeDatabaseError: relation "SequelizeMeta" already exists
    at Query.formatError (/var/www/api/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at .<anonymous> (/var/www/api/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Query.handleError (/var/www/api/node_modules/pg/lib/query.js:125:8)
    at .<anonymous> (/var/www/api/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Socket.<anonymous> (/var/www/api/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
    name: 'SequelizeDatabaseError',
            message: 'relation "SequelizeMeta" already exists',
        parent:
    { error: relation "SequelizeMeta" already exists
        at Connection.parseE (/var/www/api/node_modules/pg/lib/connection.js:539:11)
        at Connection.parseMessage (/var/www/api/node_modules/pg/lib/connection.js:366:17)
        at Socket.<anonymous> (/var/www/api/node_modules/pg/lib/connection.js:105:22)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at readableAddChunk (_stream_readable.js:172:18)
        at Socket.Readable.push (_stream_readable.js:130:10)
        at TCP.onread (net.js:542:20)
        name: 'error',
                length: 99,
            severity: 'ERROR',
            code: '42P07',
            detail: undefined,
            hint: undefined,
            position: undefined,
            internalPosition: undefined,
            internalQuery: undefined,
            where: undefined,
            schema: undefined,
            table: undefined,
            column: undefined,
            dataType: undefined,
            constraint: undefined,
            file: 'heap.c',
            line: '901',
            routine: 'heap_create_with_catalog',
            sql: 'CREATE TABLE "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , UNIQUE ("name"), PRIMARY KEY ("name"));' },
    original:
    { error: relation "SequelizeMeta" already exists
        at Connection.parseE (/var/www/api/node_modules/pg/lib/connection.js:539:11)
        at Connection.parseMessage (/var/www/api/node_modules/pg/lib/connection.js:366:17)
        at Socket.<anonymous> (/var/www/api/node_modules/pg/lib/connection.js:105:22)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at readableAddChunk (_stream_readable.js:172:18)
        at Socket.Readable.push (_stream_readable.js:130:10)
        at TCP.onread (net.js:542:20)
        name: 'error',
                length: 99,
            severity: 'ERROR',
            code: '42P07',
            detail: undefined,
            hint: undefined,
            position: undefined,
            internalPosition: undefined,
            internalQuery: undefined,
            where: undefined,
            schema: undefined,
            table: undefined,
            column: undefined,
            dataType: undefined,
            constraint: undefined,
            file: 'heap.c',
            line: '901',
            routine: 'heap_create_with_catalog',
            sql: 'CREATE TABLE "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , UNIQUE ("name"), PRIMARY KEY ("name"));' },
    sql: 'CREATE TABLE "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , UNIQUE ("name"), PRIMARY KEY ("name"));' }
```

**Comment by mkay581** [comment]
Nevermind, turns out that my PostgreSQL version was a little behind the curve. Upgrading to latest solved it.
