### ISSUE TITLE
Verbose compilation error

### ISSUE THREAD

**Issue by jonyrock** [sequelize/cli#330]
Can you  find something useful in this error message? )

```
[SyntaxError: Unexpected token )]
```

So it would be great go get normal node error output like this

```
20160722093739-story-name-title-mv.js:20
      .renameColumn('stories', 'title', 'name'));
                                               ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by vvscode** [comment]
`      .renameColumn('stories', 'title', 'name'));`

`      .renameColumn('stories', 'title', 'name');` 

?
