### ISSUE TITLE
queryInterface.removeIndex Doesn't respect custom index name for unique

### ISSUE THREAD

**Issue by chrisforrette** [sequelize/cli#332]
I came across what I believe is a bug today that I didn't find represented in issues already. Basically I added a named unique index to a model field:

``` js
const User = sequelize.define('user', {
    /* ... */

    email: {
      type: DataTypes.CHAR(255),
      allowNull: true,
    }
  }, {
    indexes: [
      /* ... */
      {
        name: 'email_index',
        fields: ['email'],
        unique: true,
      }
    ]
});
```

Then created the following migration:

``` js
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.addIndex('users', ['email'], {
      indexName: 'email_index',
      indicesType: 'UNIQUE'
    });
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.removeIndex('users', ['email'], {
      indexName: 'email_index',
      indicesType: 'UNIQUE'
    });
  }
};
```

Then I tried going forwards, then backwards, and got the following error:

``` bash
Unhandled rejection SequelizeDatabaseError: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'users_email'; check that column/key exists
    at Query.formatError (/path/to/project/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/path/to/project/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/path/to/project/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query.ErrorPacket (/path/to/project/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/path/to/project/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/path/to/project/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/path/to/project/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/path/to/project/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
```

It appears it's using an internal name, `users_email` as opposed to my specified name, `email_index`, in the `removeIndex` call and failing to drop the index. Not a horrible one by any means, I just removed the custom name, but thought I should report it anyway.

Running Node 4.4.7, Sequelize CLI 2.4.0, and Sequelize ORM 3.23.6

Thanks!

**Comment by diosney** [comment]
Same here and sadly I can't remove the custom name since it generates a long name that exceeds the maximum allowed by the DB.

**Comment by sushantdhiman** [comment]
http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-addIndex

I think it honors index name now
