### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by golergka** [sequelize/cli#427]
[Here's the previous issue about this error in the main sequelize repo](https://github.com/sequelize/sequelize/issues/4123). Since it's been closed more than 6 months ago, I was advised to create a new one.

## What you are doing?

I'm trying to run a migration:

```js
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    return [queryInterface.changeColumn('users', 'action_count', {
      defaultValue: 0
    })];
  },

  down: function (queryInterface, Sequelize) {
    return [queryInterface.changeColumn('users', 'action_count', {
      defaultValue: null
    })];
  }
}
```

## What do you expect to happen?

I was expecting the migration to run successfully.

## What is actually happening?

```
$ sequelize db:migrate

Sequelize [Node: 6.9.5, CLI: 2.5.1, ORM: 3.8.0, mysql: 2.5.0]

Loaded configuration file "config\config.json".
Using environment "development".
== 20170223082611-add-default-value-to-action-count-in-users: migrating =======
TypeError: Cannot read property 'key' of undefined
    at Sequelize.normalizeDataType (c:\idollz-server\node_modules\sequelize\lib\sequelize.js:1211:24)
    at QueryInterface.changeColumn (c:\idollz-server\node_modules\sequelize\lib\query-interface.js:382:51)
    at Object.up (c:\idollz-server\migrations\20170223082611-add-default-value-to-action-count-in-users.js:5:28)
    at constructor._exec (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\umzug\lib\migration.js:103:23)
    at constructor.up (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\umzug\lib\migration.js:69:17)
    at constructor.<anonymous> (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\umzug\index.js:124:28)
    at PassThroughHandlerContext.finallyHandler (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:431:57)
    at Promise._settlePromiseFromHandler (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:431:57)
    at Promise._settlePromiseFromHandler (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (c:\Users\max\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\promise.js:567:18)
```

__Dialect:__ mysql
__Database version:__
```
+-------------------------+------------------------------+
| Variable_name           | Value                        |
+-------------------------+------------------------------+
| innodb_version          | 5.7.17                       |
| protocol_version        | 10                           |
| slave_type_conversions  |                              |
| tls_version             | TLSv1,TLSv1.1                |
| version                 | 5.7.17-log                   |
| version_comment         | MySQL Community Server (GPL) |
| version_compile_machine | x86_64                       |
| version_compile_os      | Win64                        |
+-------------------------+------------------------------+
```
__Sequelize CLI version:__ 2.5.1

**Comment by golergka** [comment]
I was able to fix it by explicitly specifying attribute type. Here's the version that works:

```js
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    return [queryInterface.changeColumn('users', 'action_count', {
      type: Sequelize.INTEGER,
      defaultValue: 0,
      allowNull: false
    })];
  },

  down: function (queryInterface, Sequelize) {
    return [queryInterface.changeColumn('users', 'action_count', {
      type: Sequelize.INTEGER,
      defaultValue: null,
      allowNull: true
    })];
  }
}
```

I use Sequelize of version 3.8.0, so this might be fixed in later versions. Bug's source is [here](https://github.com/sequelize/sequelize/blob/343881f9dad45a4b799b92908912dc333035da6c/lib/query-interface.js#L382). `QueryInterface.changeColumn` assumes that there's always field 'type' in `dataTypeOrOptions`. However, when I'm changing the column, I don't necessarily specify the type.

**Comment by cjrutherford** [comment]
I too have this issue. my migration code is as follows:

```
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Areas', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      areaCode: {
        type: Sequelize.NUMBER,
        allowNull: false
      },
      lat: {
        type: Sequelize.STRING,
        allowNull: false
      },
      long: {
        type: Sequelize.STRING,
        allowNull: false
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('areas');
  }
};

```

My Specific Error Output:

```
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Areas', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      areaCode: {
        type: Sequelize.NUMBER,
        allowNull: false
      },
      lat: {
        type: Sequelize.STRING,
        allowNull: false
      },
      long: {
        type: Sequelize.STRING,
        allowNull: false
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('areas');
  }
};
```

CLI: 3.2.0
ORM: 4.23.4
Node: 8.6.0
