### ISSUE TITLE
Migrate not aborted on errors

### ISSUE THREAD

**Issue by igordovgaluk** [sequelize/cli#467]
migrations not aborted on errors. All migration scripts executed.
As a user I expect migration should abort on the first error. 
Unless '--ignore-errors' is used.
The failed script should not be tracked as applied.

```
== addXColumn: migrating =======
Unhandled rejection SequelizeDatabaseError: column "X" of relation "Y" already exists
    at Query.formatError (<path>/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (<path>/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:188:7)
    at Query.handleError (<path>/node_modules/pg/lib/query.js:108:8)
    at Connection.<anonymous> (<path>/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (<path>/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
From previous event:
    at Query.run (<path>/node_modules/sequelize/lib/dialects/postgres/query.js:74:17)
    at <path>/node_modules/sequelize/lib/sequelize.js:849:20
    at <path>/node_modules/retry-as-promised/index.js:40:21
From previous event:
    at retryAsPromised (<path>/node_modules/retry-as-promised/index.js:30:10)
    at <path>/node_modules/sequelize/lib/sequelize.js:848:12
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Promise.then (<path>/node_modules/sequelize/lib/promise.js:21:17)
    at Sequelize.query (<path>/node_modules/sequelize/lib/sequelize.js:845:5)
    at QueryInterface.addColumn (<path>/node_modules/sequelize/lib/query-interface.js:354:25)
    at Object.up (<path>/migrations/addXColumn.js:5:24)
    at constructor._exec (/usr/lib/node_modules/sequelize-cli/node_modules/umzug/lib/migration.js:104:23)
    at constructor.up (/usr/lib/node_modules/sequelize-cli/node_modules/umzug/lib/migration.js:69:17)
    at constructor.<anonymous> (/usr/lib/node_modules/sequelize-cli/node_modules/umzug/index.js:124:28)
== addXColumn: migrated (0.022s)

...continues with other migration scripts
```

**Comment by mcorner** [comment]
I too have run into this...  At the moment my workaround is to use a transaction in the migration, which ensures that the whole migration runs or it doesn't *and* an unhandedRejection handler to make sure that the cli doesn't just run the rest of the migrations anyway.

Hopefully there is a better way?

```
'use strict';

process.on('unhandledRejection', error => {
  console.log(error.message);
  process.exit(1);
});

module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.sequelize.transaction(function handleTransaction (t) {
      return queryInterface.createTable('baz', {}, {transaction: t}).then(() =>{
        queryInterface.removeColumn('foo', 'bar', {transaction: t});
      });
    });
  },
};
```

**Comment by Americas** [comment]
@igordovgaluk Looking at the `Unhandled rejection` part of the error makes me think that you are not using promises correctly, but I can't say for sure without looking at the code.

**Comment by igordovgaluk** [comment]
@Americas the issue is about the migrations should stop if one of the steps has failed.

**Comment by Americas** [comment]
Yes, and I'm saying that if you don't return the promise chain, then the client will assume that the migration ran without problems, and keep on going. I cannot say for sure without seeing the code. But if that is the case, then it would explain why the migrations keep running even when one fails.

**Comment by sushantdhiman** [comment]
It seems promise are not correctly returned in up / down function, we cant really handle errors if you dont return promise properly
