### ISSUE TITLE
config.json not read properly

### ISSUE THREAD

**Issue by framled** [sequelize/cli#474]
When I run `db:migrate` the config.js file is not read properly and get this error:

```
./node_modules/sequelize-cli/bin/sequelize db:migrate

Sequelize [Node: 7.10.0, CLI: 2.7.0, ORM: 4.2.0]

Loaded configuration file "config/config.json".
Using environment "development".
== 20170621004045-init: migrating =======
{ SequelizeAccessDeniedError: Access denied for user ''@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/path/to/my/project/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:138:17)
    at tryCatcher (/path/to/my/project/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/path/to/my/project/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/path/to/my/project/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/path/to/my/project/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/path/to/my/project/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/path/to/my/project/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/path/to/my/project/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/path/to/my/project/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  name: 'SequelizeAccessDeniedError',
  parent: 
   { Error: Access denied for user ''@'localhost' (using password: NO)
       at Packet.asError (/path/to/my/project/node_modules/mysql2/lib/packets/packet.js:701:13)
       at ClientHandshake.Command.execute (/path/to/my/project/node_modules/mysql2/lib/commands/command.js:28:22)
       at Connection.handlePacket (/path/to/my/project/node_modules/mysql2/lib/connection.js:500:28)
       at PacketParser.onPacket (/path/to/my/project/node_modules/mysql2/lib/connection.js:94:16)
       at PacketParser.executeStart (/path/to/my/project/node_modules/mysql2/lib/packet_parser.js:77:14)
       at Socket.<anonymous> (/path/to/my/project/node_modules/mysql2/lib/connection.js:102:29)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at TCP.onread (net.js:561:20)
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '#28000' },
  original: 
   { Error: Access denied for user ''@'localhost' (using password: NO)
       at Packet.asError (/path/to/my/project/node_modules/mysql2/lib/packets/packet.js:701:13)
       at ClientHandshake.Command.execute (/path/to/my/project/node_modules/mysql2/lib/commands/command.js:28:22)
       at Connection.handlePacket (/path/to/my/project/node_modules/mysql2/lib/connection.js:500:28)
       at PacketParser.onPacket (/path/to/my/project/node_modules/mysql2/lib/connection.js:94:16)
       at PacketParser.executeStart (/path/to/my/project/node_modules/mysql2/lib/packet_parser.js:77:14)
       at Socket.<anonymous> (/path/to/my/project/node_modules/mysql2/lib/connection.js:102:29)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at TCP.onread (net.js:561:20)
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '#28000' } }
```

this is my config.json file
```
{
  "development": {
    "username": "root",
    "password": "password",
    "database": "database_development",
    "host": "127.0.0.1",
    "dialect": "mysql"
  },
  "test": {
    "username": "root",
    "password": null,
    "database": "database_test",
    "host": "127.0.0.1",
    "dialect": "mysql"
  },
  "production": {
    "username": "root",
    "password": null,
    "database": "database_production",
    "host": "127.0.0.1",
    "dialect": "mysql"
  }
}
`
``

**Comment by sushantdhiman** [comment]
I have ran migrations and config.js is properly read. Need more info about setup
