### ISSUE TITLE
Error: Cannot find module \models/..configconfig.json'

### ISSUE THREAD

**Issue by xSlok** [sequelize/cli#494]
Hi all,
I created an express project, added the postgresql and sequelize dependencies and addded this line to bin/www: var models = require('../models');
when I run the project, I get this error: 

module.js:471
    throw err;
    ^

Error: Cannot find module '*project folder*\models/..configconfig.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (*project folder*\models\index.js:8:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (*project folder*\bin\www:10:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

```
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vigiacascavel@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vigiacascavel@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vigiacascavel package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vigiacascavel
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vigiacascavel
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     *project folder*\npm-debug.log
```

and this is my full package.json: 
```
{
  "name": "projeto",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.17.1",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.3",
    "ejs": "~2.5.6",
    "express": "~4.15.2",
    "morgan": "~1.8.1",
    "serve-favicon": "~2.4.2",
	"pg": "^7.0.2",
    "pg-hstore": "^2.3.2",
    "sequelize": "^3.23.6",
    "sequelize-cli": "^2.4.0"
  }
}
```

Here's my project file
[projeto.zip](https://github.com/sequelize/cli/files/1185053/projeto.zip)

Sorry if this is a dumb error, i'm new to using sequelize.

thanks!

**Comment by xSlok** [comment]
Solved the problem, for some reason the config file path on index.js was created with \ instead of /
