### ISSUE TITLE
db:migrate --config crashes

### ISSUE THREAD

**Issue by asifmohd** [sequelize/cli#517]
Sequelize-cli 2.8.0 crashes when running
`sequelize db:migrate --config config/mysqlConf.js`

```
Loaded configuration file "config/mysqlConf.js".
TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:5)
    at new Sequelize (/www/app/node_modules/sequelize/lib/sequelize.js:104:22)
    at getSequelizeInstance (/www/app/node_modules/sequelize-cli/lib/tasks/db.js:394:12)
    at getMigrator (/www/app/node_modules/sequelize-cli/lib/tasks/db.js:403:21)
    at Object.task (/www/app/node_modules/sequelize-cli/lib/tasks/db.js:23:14)
    at /www/app/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:23
    at tryCatcher (/www/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/www/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/www/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/www/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/www/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/www/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/www/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/www/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
'db:migrate' errored after 7.55 ms
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:5)
    at new Sequelize (/www/app/node_modules/sequelize/lib/sequelize.js:104:22)
    at getSequelizeInstance (/www/app/node_modules/sequelize-cli/lib/tasks/db.js:394:12)
    at getMigrator (/www/app/node_modules/sequelize-cli/lib/tasks/db.js:403:21)
    at Object.task (/www/app/node_modules/sequelize-cli/lib/tasks/db.js:23:14)
    at /www/app/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:23
    at tryCatcher (/www/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/www/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/www/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/www/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/www/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/www/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/www/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/www/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

npm info lifecycle myapp@0.0.0~migrations: Failed to exec migrations script
npm ERR! Linux 4.4.65-k8s
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "migrations"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! myapp@0.0.0 migrations: `sequelize db:migrate --config config/mysqlConf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myapp@0.0.0 migrations script 'sequelize db:migrate --config config/mysqlConf.js'.
```

Meanwhile Sequelize-cli 2.7.0 does not crash

Attaching the debug log as well
[debug.txt](https://github.com/sequelize/cli/files/1231645/debug.txt)

**Comment by asifmohd** [comment]
Attaching a config file which reproduces the crash
[config.txt](https://github.com/sequelize/cli/files/1233564/config.txt)

**Comment by sushantdhiman** [comment]
`host: mysql`

**Comment by asifmohd** [comment]
So i finally figured out the issue, leaving this comment here, in case someone else also faces the same problem.

We were using an older sequelize version i.e. `2.1.3`
Updating sequelize to `3.30.4`, and cli to `3.0.0` seems to have fixed this issue
