### ISSUE TITLE
Error on init

### ISSUE THREAD

**Issue by postal2600** [sequelize/cli#59]
I am running sequelize-cli v0.3.3. When I call `node_modules/.bin/sequelize init` I get the following error:

    /home/postal/Dropbox/Area51/MyProj/node_modules/sequelize-cli/node_modules/gulp/node_modules/liftoff/index.js:141
        throw new Error('You must provide a callback function.');
              ^
    Error: You must provide a callback function.
        at Liftoff.launch (/home/postal/Dropbox/Area51/MyProj/node_modules/sequelize-cli/node_modules/gulp/node_modules/liftoff/index.js:141:11)
        at Object.<anonymous> (/home/postal/Dropbox/Area51/MyProj/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:26:5)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:901:3

**Comment by sdepold** [comment]
Hey @postal2600,

since this ticket has been opened we have introduced quite some changes. Can you retry the code with the latest version from npm? Also: I'm not so sure what you mean but gulp 3.6.2 is not too awfully old. current version is 3.8.x (https://www.npmjs.com/package/gulp). Please re-open the ticket if the issue is still a thing.

**Comment by postal2600** [comment]
I will try it one of this days. Thank you for the updates!
