### ISSUE TITLE
Migration passes when the SQL is wrong?

### ISSUE THREAD

**Issue by djvs** [sequelize/cli#626]
## What you are doing?

$ sequelize db:migrate
sequelize:unset:1: no such hash table element: yarn

Sequelize CLI [Node: 7.9.0, CLI: 4.0.0, ORM: 4.33.4]

Loaded configuration file "config/config.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
File: .20180310151704-addUrlToChannels.js.swp does not match pattern: /\.js$/
File: .20180310151704-addUrlToChannels.js.swp does not match pattern: /\.js$/
File: .20180310151704-addUrlToChannels.js.swp does not match pattern: /\.js$/
== 20180310151704-addUrlToChannels: migrating =======
Unhandled rejection SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Sequelize.STRING' at line 1
    at Query.formatError (/srv/csommers/api/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/srv/csommers/api/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/srv/csommers/api/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/srv/csommers/api/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/srv/csommers/api/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/srv/csommers/api/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/srv/csommers/api/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)

== 20180310151704-addUrlToChannels: migrated (0.105s)

$ sequelize db:migrate:undo

Sequelize CLI [Node: 7.9.0, CLI: 4.0.0, ORM: 4.33.4]

Loaded configuration file "config/config.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
File: .20180310151704-addUrlToChannels.js.swp does not match pattern: /\.js$/
File: .20180310151704-addUrlToChannels.js.swp does not match pattern: /\.js$/
== 20180310151704-addUrlToChannels: reverting =======
Unhandled rejection SequelizeDatabaseError: Can't DROP 'url'; check that column/key exists
    at Query.formatError (/srv/csommers/api/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/srv/csommers/api/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/srv/csommers/api/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/srv/csommers/api/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/srv/csommers/api/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/srv/csommers/api/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/srv/csommers/api/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)

== 20180310151704-addUrlToChannels: reverted (0.163s)

## What do you expect to happen?
Migration shouldn't mark as succeeded and be inserted into DB (or vice versa).

## What is actually happening?
Migration entry added into DB then removed even though migration failed

__Dialect:__ mysql
__Database version:__ 5.7.19-log MySQL Community Server (GPL)  - a MariaDB 
__Sequelize CLI version:__ 4.0.0
__Sequelize version:__ 4.33.4

**Comment by honcharov-viktor** [comment]
I have same problem.
**Dialect**: postgres
**Database version**: PostgreSQL 9.3
**Sequelize CLI version**: 4.0.0
**Sequelize version**: 4.33.41

**Comment by sushantdhiman** [comment]
> Unhandled rejection 

Means you are not returning promise correctly in `up / down` methods
