### ISSUE TITLE
Error: cannot find module 'tedious'

### ISSUE THREAD

**Issue by jmorton25** [sequelize/cli#631]
I can't seem to get the seed or migrate CLI commands to work: ie sequelize db:seed, sequelize db:migrate, etc.

I've tried recreating my package.json, installing via yarn and npm, installing packages in different orders, but no luck. Below is my package.json and a debug trace. 

I'm on a Windows machine, and our other developers on Mac don't seem to be having the same problem -- not sure if that could be related at all. 

Let me know if there's any further info I can provide that would be helpful. 

```
{
  "name": ""
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": ""
  },
  "engines": {
    "node": ">= 8.9.0"
  },
  "scripts": {
    "start:dev": "nodemon ./bin/www",
    "start": "node ./bin/www"
  },
  "dependencies": {
    "bcrypt": "^1.0.3",
    "bcrypt-promise": "^2.0.0",
    "body-parser": "^1.18.2",
    "express": "^4.16.2",
    "jsonwebtoken": "^8.2.0",
    "lodash": "^4.17.5",
    "morgan": "^1.9.0",
    "npm": "^5.7.1",
    "passport": "^0.4.0",
    "passport-jwt": "^3.0.1",
    "sequelize": "^4.37.1",
    "sequelize-cli": "^4.0.0",
    "tedious": "^2.3.1"
  },
  "devDependencies": {
    "nodemon": "^1.17.1"
  }
}
```

Debug error trace is below:
```
Sequelize CLI [Node: 8.9.4, CLI: 4.0.0, ORM: 4.36.1]

Loaded configuration file "server\config\config.json".
Using environment "development".

ERROR: Error: Cannot find module 'tedious'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\josh.morton\AppData\Roaming\npm\node_modules\sequelize\lib\dialects\mssql\query.js:11:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\josh.morton\AppData\Roaming\npm\node_modules\sequelize\lib\dialects\mssql\index.js:6:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at new Sequelize (C:\Users\josh.morton\AppData\Roaming\npm\node_modules\sequelize\lib\sequelize.js:224:19)
    at getSequelizeInstance (C:\Users\josh.morton\AppData\Roaming\npm\node_modules\sequelize-cli\lib\core\migrator.js:49:12)
    at C:\Users\josh.morton\AppData\Roaming\npm\node_modules\sequelize-cli\lib\core\migrator.js:62:21
    at tryCatcher (C:\Users\josh.morton\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\josh.morton\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\bluebird\js\release\method.js:39:29)
    at getMigrator (C:\Users\josh.morton\AppData\Roaming\npm\node_modules\sequelize-cli\lib\core\migrator.js:56:32)
    at Object.<anonymous> (C:\Users\josh.morton\AppData\Roaming\npm\node_modules\sequelize-cli\lib\commands\seed_one.js:43:41)
    at Generator.next (<anonymous>)
```

**Comment by luizfilipe** [comment]
Any updates on that? I'm getting the same error but tedious is installed!

**Comment by jmorton25** [comment]
@luizfilipe I was able to work around this by installing sequelize-cli locally instead of globally, then running the seed commands from the node_modules directory version of sequelize-cli:

.\node_modules\.bin\sequelize db:seed:all

**Comment by sushantdhiman** [comment]
Install cli / sequelize / dialect locally http://docs.sequelizejs.com/manual/tutorial/migrations.html
