### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by ricardomoura** [sequelize/cli#633]
hey guys, using windows 10 at home and i'm having this error:
on the mac is ok

```
λ yarn -v
1.3.2
λ node -v
v9.5.0
λ npm -v
5.6.0
λ mkdir tmp
λ cd tmp
λ yarn add sequelize-cli sequelize pg
λ node node_modules/.bin/sequelize init
C:\Users\rmoura\Code\tmp\node_modules\.bin\sequelize:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
```
any ideias of what is it? thanks

**Comment by leonardorb** [comment]
Any leads on this, folks? Some Windows machines are having the same issue.

**Comment by mikew** [comment]
Any reason you are running `.bin/sequelize` with node? It looks like it's a bash script.

Does a plain `node_modules/.bin/sequelize init` work?

**Comment by ricardomoura** [comment]
@mikew will test soon im able to
