### ISSUE TITLE
No file, line number, or line code shown for errors in migration files

### ISSUE THREAD

**Issue by broofa** [sequelize/cli#675]
## What you are doing?

Trying to debug errors in migration files is made unnecessarily difficult due to a lack of error information.  For example, create and edit a new migration:
```
> sequelize migration:generate --name foo`
> vi db/migrations/*-foo.js
```
Add some bad code (syntax error, whatever):

```js
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    BARF
  },
};
```

Run the migration:
```
> sequelize db:migrate

Sequelize CLI [Node: 8.11.1, CLI: 4.0.0, ORM: 4.38.0]

(--- snip ---)

Using environment "development".
== 20180719212038-foo: migrating =======

ERROR: BARF is not defined
```

## What do you expect to happen?

Errors should include all the usual context about where the error occured - file, line number, and line code information - like so:
```
> node -e "require('./db/migrations/20180719212038-foo.js').up()"
/Users/kieffer/tend/code/boss/db/migrations/20180719212038-foo.js:5
    BARF
    ^

ReferenceError: BARF is not defined
    at Object.up (/Users/kieffer/tend/code/boss/db/migrations/20180719212038-foo.js:5:5)
    at [eval]:1:50
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:463:27)
    at startup (bootstrap_node.js:164:9)
    at bootstrap_node.js:609:3
```

## What is actually happening?

`sequelize` only shows the error message and nothing else. 

__Dialect:__ any
__Database version:__ na
__Sequelize CLI version:__ CLI: 4.0.0
__Sequelize version:__ na

**Comment by broofa** [comment]
Okay, I've found the `--debug` flag, which enables stack trace info, but it took a bit of [groveling through the code](https://github.com/sequelize/cli/blob/7160d00d417ac59adb8d63ef07220a90aa2a0be8/src/helpers/view-helper.js#L35).

It looks like this might be an [intentional] regression [introduced back in Sept](https://github.com/sequelize/cli/commit/5633648ecb6d81b3fdeafadd5ee1c9e6fb350dd5#diff-2f6394cb44960f14c1b7f107c7435165L29).  Why isn't the stack being logged any more?  That seems almost sadistic. :-(
