### ISSUE TITLE
"url" key in config just work with sequelize and not with sequelize-cli.

### ISSUE THREAD

**Issue by frederikhors** [sequelize/cli#688]
If I use this:

_config.js:_
```js
module.exports = {
  development: {
    url: "postgres://postgres:postgres@localhost/my_db",
    dialect: 'postgres'
  }
}
```

It gives me this:

```log
Sequelize CLI [Node: 10.9.0, CLI: 4.1.1, ORM: 4.38.0]

Loaded configuration file "config\sequelize.js".
Using environment "development".
Unhandled rejection TypeError: Cannot read property 'replace' of undefined
    at Object.removeTicks (project\node_modules\sequelize\lib\utils.js:415:12)
    at Object.quoteIdentifier (project\node_modules\sequelize\lib\dialects\postgres\query-generator.js:872:35)
    at QueryInterface.quoteIdentifier (project\node_modules\sequelize\lib\query-interface.js:1323:32)
    at Object.<anonymous> (project\node_modules\sequelize-cli\lib\commands\database.js:48:78)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (project\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (project\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (project\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (project\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (project\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (project\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (project\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (project\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)

Done in 2.41s.
```

If I use the default:

```js
module.exports = {
  development: {
    username: 'postgres',
    password: 'postgres',
    database: 'mydb',
    host: 'localhost',
    dialect: 'postgres'
  }
}
```

it works good with `sequelize-cli`.

The config works good both with `sequelize` instead.

**Comment by adrianodennanni** [comment]
@frederikhors if you solved this, could you please share your solution?

**Comment by bismark** [comment]
I got this same error when using `db:create`. I believe this is due to the `db:create` requiring a `database` key even when the `url` is defined, see https://github.com/sequelize/cli/blob/77a9a76420e36cfbcb82fe3c9c6a12d52c768104/src/commands/database.js#L88. If you add just `database` it will still correctly connect to the database using the url.

**Comment by samuliasmala** [comment]
If you want to use url for sequelize-cli one option is to define it in _.sequelizerc_

```js

module.exports = {
  'url': 'postgres://postgres:postgres@localhost/my_db',
};
```
