### ISSUE TITLE
perform command 'db:create'  create database fail

### ISSUE THREAD

**Issue by shiyunn** [sequelize/cli#692]
## What you are doing?
perform command 'db:create'
```js
sequelize db:create
```

## What do you expect to happen?
I want create database success;

## What is actually happening?
show below error message for me; create database fail
```
Unhandled rejection TypeError: Cannot read property 'replace' of undefined
    at Object.removeTicks (/Volumes/shi/WebDemo/hapi-mini/node_modules/sequelize/lib/utils.js:415:12)
    at Object.quoteIdentifier (/Volumes/shi/WebDemo/hapi-mini/node_modules/sequelize/lib/dialects/mysql/query-generator.js:393:33)
    at QueryInterface.quoteIdentifier (/Volumes/shi/WebDemo/hapi-mini/node_modules/sequelize/lib/query-interface.js:1323:32)
    at Object.<anonymous> (/Volumes/shi/WebDemo/hapi-mini/node_modules/sequelize-cli/lib/commands/database.js:38:80)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Volumes/shi/WebDemo/hapi-mini/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Volumes/shi/WebDemo/hapi-mini/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Volumes/shi/WebDemo/hapi-mini/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Volumes/shi/WebDemo/hapi-mini/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Volumes/shi/WebDemo/hapi-mini/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Volumes/shi/WebDemo/hapi-mini/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Volumes/shi/WebDemo/hapi-mini/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Volumes/shi/WebDemo/hapi-mini/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Volumes/shi/WebDemo/hapi-mini/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

__Dialect:__ mysql 
__Database version:__ 5.7
__Sequelize CLI version:__ 4.1.1
__Sequelize version:__ 4.38.1

**Comment by manast-apsis** [comment]
Hit by this issue too. I guess we will need to provide a complete reproducible example.

**Comment by SerenaG** [comment]
If this can help someone else, this issue was because I've had an _undefined_ property in the config file.

**Comment by cjancsar** [comment]
@SerenaG can you post your old config file? As that is a vague example... :(

**Comment by Powers-RC** [comment]
@SerenaG any update on how resolved this? I am running into the same issue.
