### ISSUE TITLE
Attribute 'role:enum:Admin' cannot be parsed: Unknown type 'Admin'

### ISSUE THREAD

**Issue by majidsajadi** [sequelize/cli#738]
## What you are doing?
I wanted to run tests. I cloned the repository and installed the node modules then run test.

## What do you expect to happen?
All tests pass.

## What is actually happening?
290 test passed. But apparently one test related to creating model failed.

console log:

```
  290 passing (9m)
  1 failing

  1) [SQLITE] lib/sequelize model:create
       attributes
         --attributes first_name:string,last_name:string,bio:text,role:enum:{Admin,"Guest User"},reviews:array:text
           exits with exit code 0:
     Uncaught Error: Command failed: /Users/macbook/workspace/cli/lib/sequelize model:create --name User --attributes first_name:string,last_name:string,bio:text,role:enum:{Admin,"Guest User"},reviews:array:text
ERROR: Attribute 'role:enum:Admin' cannot be parsed: Unknown type 'Admin'

      at ChildProcess.exithandler (child_process.js:289:12)
      at ChildProcess.EventEmitter.emit (domain.js:442:20)
      at maybeClose (internal/child_process.js:962:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

```

**Comment by SimonSchick** [comment]
@sushantdhiman also running into this.

**Comment by majidsajadi** [comment]
No feedback? i clone and run test again. Tests didn`t pass again.
