### ISSUE TITLE
'ALTER TYPE ... ADD' error in PostgreSQL when migrating

### ISSUE THREAD

**Issue by seonggukchoi** [sequelize/cli#770]
## What you are doing?

```js
  up: (queryInterface, Sequelize) => {
    const query = `
      ALTER TYPE "my_enum_type"
      ADD VALUE 'a1';
      ALTER TYPE "my_enum_type"
      ADD VALUE 'b2';
    `;
    return queryInterface.sequelize.query(query);
  },
```

## What do you expect to happen?
I want to add value to ENUM type.

## What is actually happening?
```
ERROR: SequelizeDatabaseError: ALTER TYPE ... ADD cannot run inside a transaction block
    at Query.formatError (/Users/my-project/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)
    at query.catch.err (/Users/my-project/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/Users/my-project/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/my-project/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/my-project/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/my-project/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/my-project/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/my-project/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/my-project/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/my-project/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/my-project/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

__Dialect:__ postgres
__Database version:__ 11.2
__Sequelize CLI version:__ 5.4.0
__Sequelize version:__ 4.42.0

**Comment by seonggukchoi** [comment]
I was check this error at just querying `ALTER TYPE ... ADD`.
I can't found error at querying `ALTER TYPE ... RENAME TO ...`.

**Comment by danielrearden** [comment]
For anyone else encountering this issue, you can split up your statements to one per query to avoid them getting wrapped in a transaction:

```
up: async (queryInterface, Sequelize) => {
  await queryInterface.sequelize.query(`
    ALTER TYPE "my_enum_type" ADD VALUE 'a1';
  `);
  await queryInterface.sequelize.query(`
    ALTER TYPE "my_enum_type" ADD VALUE 'b2';
  `);
}
```
