### ISSUE TITLE
OOM when running .findAll on large database

### ISSUE THREAD

**Issue by korroktheslavemaster** [sequelize/cli#796]
## What you are doing?

I have around ~1000 objects in a table, each ~2MB in size. When I run `Model.findAll` on the model, I get `RangeError: Array buffer allocation failed`.
Is there a way to sequentially iterate over the objects instead of fetching them all at once?
For testing purposes, all I'm doing in my migration is `findAll` and returning it. So my migration file looks like this:
```
"use strict";
require("babel-polyfill");

import { Map } from "../models/index";

module.exports = {
  up: async () => {
    var maps = await Map.findAll();
    return;
  },

  down: async () => {
    return;
  }
};
```
Then I'm running
```
sequelize db:migrate
```
All I want to do is iterate on the objects and modify some properties.

## What do you expect to happen?
Migration to succeed

## What is actually happening?
```
Sequelize CLI [Node: 9.11.1, CLI: 4.1.1, ORM: 4.43.1]

Loaded configuration file "config/config.js".
Using environment "production".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators ../node_modules/sequelize/lib/sequelize.js:242:13
== 20190702131655-rename-ods-to-ods-excluded: reverting =======
buffer.js:67
    super(arg1, arg2, arg3);
    ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at typedArrayConstructByLength (<anonymous>)
    at new Uint8Array (native)
    at new FastBuffer (buffer.js:67:5)
    at Function.alloc (buffer.js:267:10)
    at module.exports.Reader.addChunk (/app/node_modules/packet-reader/index.js:35:28)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:117:18)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapcreator-react@1.0.0 undo-migrate: `cd server && sequelize db:migrate:undo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapcreator-react@1.0.0 undo-migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-03T10_29_55_632Z-debug.log
```

**Comment by eseliger** [comment]
You can utilize offset and limit parameters to implement pagination
