### ISSUE TITLE
db:migrate's errors when `new Sequelize` fails is uninformative

### ISSUE THREAD

**Issue by dantman** [sequelize/cli#98]
```$ sequelize db:migrate

Sequelize [Node: 0.12.0, CLI: 1.2.0, ORM: 2.0.0-rc8]

Loaded configuration file 'sequelize-config.js'.
Using environment 'development'.
    at new module.exports.Sequelize (./node_modules/sequelize/lib/sequelize.js:191:13)
    at getSequelizeInstance (/usr/local/lib/node_modules/sequelize-cli/lib/tasks/db.js:180:10)
    at getMigrator (/usr/local/lib/node_modules/sequelize-cli/lib/tasks/db.js:185:21)
    at Object.module.exports.db:migrate.task (/usr/local/lib/node_modules/sequelize-cli/lib/tasks/db.js:23:7)
    at Gulp.gulp.task.aliases (/usr/local/lib/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:14:14)
    at module.exports (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

```

Whenever db:migrate fails to create Sequelize (because the type is incorrect, the dialect's connector is not installed, etc...) the error appears to be printed without the error's message.
```

**Comment by sdepold** [comment]
I think I know why this happens. Will try to work on a fix soon.

**Comment by MrOrz** [comment]
@sdepold Any progress on this? This happens to me as well.

**Comment by jakerobers** [comment]
was this ever fixed?

**Comment by jakerobers** [comment]
I get this error when I try to use the postgres connection string ("postgres://user:pass@localhost:5432/dbname"). Fixed this by using the object-style.

**Comment by yamii** [comment]
I also get this error. Any progress?

**Comment by sushantdhiman** [comment]
Cleaning up old issues, let me know if its still an issue and I will reopen it.
